### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by ChaosCA** [yumiris/Nouveau#2]
Hey @yumiris love the project.

Was just wondering if you had copies of the higher resolution background images used. They would make a great desktop background :)

**Comment by yumiris** [comment]
Yup, they can be found [here](https://www.flickr.com/photos/joshezzellphotography/albums/72157685404546773). Credits to [Joshua Ezzell](https://www.artstation.com/joshezzell) for the images!

**Comment by ChaosCA** [comment]
Thank you!
